<a href="https://colab.research.google.com/github/LSaldiasV/Mineria_de_Datos/blob/main/ImdbDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/content/imdb_top_1000.csv")

In [40]:
df.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

In [43]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [44]:
df.shape

(1000, 16)

In [54]:
df.isnull().sum()
#vemos la cantidad de nulo por columna

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [ ]:
df.dropna()
#Con este comando eliminaremos todos los valores nullos que se encuentren en el Dataset

Las columnas categoricas que encontramos en este dataset seria la certificacion, su genero cinematografico

In [7]:
df['Certificate'].value_counts()
#Aca podemos ver que en certificacion poseemos 16 tipos de certificaciones de edad diferentes

Certificate
U           234
A           197
UA          175
R           146
PG-13        43
PG           37
Passed       34
G            12
Approved     11
TV-PG         3
GP            2
TV-14         1
Unrated       1
TV-MA         1
16            1
U/A           1
Name: count, dtype: int64

In [47]:
df['Certificate'].value_counts().count()

np.int64(16)

In [29]:
df['Certificate'].describe()
#Tenemos 899 objetos con valor y de estos son 16 categorias diferentes

count     899
unique     16
top         U
freq      234
Name: Certificate, dtype: object

Terminamos con las certificaciones y pasamos a generos

In [27]:
df['Genre'].value_counts()
#Aca podemos ver que tenemos 202 tipos de generos diferentes dentro de nuestra columna "Genre"

Genre
Drama                        85
Drama, Romance               37
Comedy, Drama                35
Comedy, Drama, Romance       31
Action, Crime, Drama         30
                             ..
Action, Adventure, Family     1
Action, Crime, Mystery        1
Animation, Drama, Romance     1
Drama, War, Western           1
Adventure, Comedy, War        1
Name: count, Length: 202, dtype: int64

In [48]:
df['Genre'].value_counts().count()

np.int64(202)

In [46]:
df['Genre'].describe()
#Podemos ver que todos los objetos tienen valores y estos pueden ser 1 de los 202 combinaciones diferentes que existen de categoria

count      1000
unique      202
top       Drama
freq         85
Name: Genre, dtype: object

Terminamos con los generos y pasamos a los directores

In [49]:
df['Director'].value_counts()
#Aca podemos encontrar que el director tambien puede ser un ente categorico, ya que muchos poseen muchas peliculas

Director
Alfred Hitchcock    14
Steven Spielberg    13
Hayao Miyazaki      11
Akira Kurosawa      10
Martin Scorsese     10
                    ..
Kinji Fukasaku       1
Eric Bress           1
Thomas Kail          1
Irvin Kershner       1
Lana Wachowski       1
Name: count, Length: 548, dtype: int64

In [51]:
df['Director'].value_counts().count()

np.int64(548)

In [52]:
df['Director'].describe()
#Aca podemos ver que de los 1000 valores en el dataset, tenemos 548 directores para categorizar cada pelicula

count                 1000
unique                 548
top       Alfred Hitchcock
freq                    14
Name: Director, dtype: object

In [59]:
df['Director'].value_counts().head(10)
#Vemos los 10 directores con mas presencia en el dataset

Director
Alfred Hitchcock     14
Steven Spielberg     13
Hayao Miyazaki       11
Akira Kurosawa       10
Martin Scorsese      10
Woody Allen           9
Stanley Kubrick       9
Billy Wilder          9
Clint Eastwood        8
Christopher Nolan     8
Name: count, dtype: int64

In [57]:
#Aca extraemos los 10 directores mas repetidos y los que no encajan en este grupo los categorizamos como otros, esto sirve, ya que al ser 548 director
#esto se engrandece mucho y aplicamos una simplificacion de datos
Top10_Directores = df['Director'].value_counts().nlargest(10).index
df['director_agrupado'] = df['Director'].apply(lambda x: x if x in Top10_Directores else 'Otros')
df['director_agrupado'].value_counts()

director_agrupado
Otros                899
Alfred Hitchcock      14
Steven Spielberg      13
Hayao Miyazaki        11
Martin Scorsese       10
Akira Kurosawa        10
Stanley Kubrick        9
Woody Allen            9
Billy Wilder           9
Christopher Nolan      8
Clint Eastwood         8
Name: count, dtype: int64